openapi: 3.0.3
info:
  title: Crawler API
  version: 1.0.0
  description: |
    API contract for Crawler MVP.
servers:
  - url: http://localhost:8080
    description: Public entrypoint
tags:
  - name: Crawls
security:
  - bearerAuth: []
paths:
  /api/crawls:
    post:
      tags: [ Crawls ]
      security: [ ]
      operationId: createCrawlingJob
      summary: Create a crawl job based on initial url
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCrawlJob'
      responses:
        '201':
          description: Crawl job created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrawlJobId'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/crawls/{jobId}:
    get:
      tags: [ Crawls ]
      security: [ ]
      operationId: getCrawlJob
      summary: Get crawl job
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Crawl job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrawlJobSimple'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/crawls/{jobId}/result:
    get:
      tags: [ Crawls ]
      security: [ ]
      operationId: getCrawlJobResult
      summary: Get crawl job result
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Crawl job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrawlJob'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NewCrawlJob:
      type: object
      properties:
        initialUrl:
          type: string
        maxDepth:
          type: integer
          format: int32
    CrawlJobId:
      type: object
      properties:
        id:
          type: string
          format: uuid
    CrawlJobSimple:
      type: object
      properties:
        id:
          type: string
          format: uuid
        initialUrl:
          type: string
        maxDepth:
          type: integer
          format: int32
        status:
          $ref: '#/components/schemas/CrawlJobStatus'
    CrawlJob:
      type: object
      properties:
        id:
          type: string
          format: uuid
        initialUrl:
          type: string
        maxDepth:
          type: integer
          format: int32
        status:
          $ref: '#/components/schemas/CrawlJobStatus'
        result:
          type: array
          items:
            $ref: '#/components/schemas/CrawlResultPage'
    CrawlJobStatus:
      type: string
      enum: [
        PENDING,
        FINISHED,
        FAILED
      ]
      x-enum-varnames: [
        PENDING,
        FINISHED,
        FAILED
      ]
    CrawlResultPage:
      type: object
      properties:
        url:
          type: string
        depth:
          type: integer
          format: int32
        links:
          type: array
          items:
            type: string
        incomingLinks:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
        error:
          type: string
        path:
          type: string
        timestamp:
          type: integer
          format: int64
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorMessage'
    ErrorMessage:
      type: object
      properties:
        message:
          type: string
        code:
          type: string